spring:
  datasource:
    password: ${user_pwd}
    url: jdbc:postgresql://db.ihmqbphkncqwubmtymvu.supabase.co:5432/postgres
    username: ${user_db}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.office365.com
    port: 587
    username: ${email_username}
    password: ${email_pwd}
    properties:
      mail:
        store: 
          protocol: pop3
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
template:
   forgot-password: forgot-password.ftl

custom-url:
   recovery-password: http://localhost:8080/forgot-password/recovery?id=%d
          
firebase:
    bucket-name: ${bucket_name}
    project-id: ${project_id}
    service-account-key: ${service_account}
    base-url: https://firebasestorage.googleapis.com/v0/b/sport-hub-11400.appspot.com/o/%s
    