spring:
  datasource:
    password: ${user_pwd}
    url: jdbc:postgresql://db.ihmqbphkncqwubmtymvu.supabase.co:5432/postgres
    username: ${user_db}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        
firebase:
    bucket-name: ${bucket_name}
    project-id: ${project_id}
    service-account-key: ${service_account}
